### PR TITLE
Template improvements

### PR DESCRIPTION
**Pull request by Train88**
Everything I've done in these commits are things that many people have been asking to be done, but have been ignored. I have done it for you.

### CODE REVIEW

**Comment by jahirfiquitiva** [comment]
1. Are you sure adding the Material Drawer theme doesn't affect the UI already available?
2. The colors you have set for it are the default ones?
3. Thanks for the fixes for the manifest, but are you sure wallpapers still downloading properly? and are you sure icon requests still work properly?
4. android.permission.WAKE_LOCK is needed for Muzei support.
5. After deleting the wifi and internet permissions are you sure everything still works properly?
6. com.android.vending.CHECK_LICENSE should be a comment since not everybody is using it. Anyways, this isn't needed because the app doesn't works with the billing library.

**Comment by Train88** [comment]
1. The material theme can be edited to change the colors to the original. I simply copied the styles from his source. 
2. The colors are mine, just to be used as a template. 
3. Yes, the wallpapers still work, but I was told the wake_lock permission was needed for muzei. 
4. Yep. 
5. I did not delete the wifi and Internet permissions, github just moved them around after my other deletions. 
6. Ok, cool. I thought it might be needed since the app has a license check in it

**Comment by jahirfiquitiva** [comment]
1 and 2 keep the original ones, or default for light theme.
3. Did you test download and applying and cropping+applying?
4. So you'll keep it?
5. I saw you deleted the ACCESS_WIFI_STATE permission, it still works?
6. No, isn't needed unless the user of the dashboard wants to include that library. But that's all up to him/her. So he/she must do it by himself/herself.

Sorry for many questions/requests, but I want to make sure everything will still work as the original template before merging this.

**Comment by Train88** [comment]
1 and 2. You just have to change the colors for it to be material light.
3. Yes, it works even on debug mode 
4. Maybe, it depends on if I decide to keep muzei. So it should actually be up to the user as well. 
5. Yes, everything with wallpapers was working 

No problem, I understand! I was just trying to provide more options for people :)

**Comment by jahirfiquitiva** [comment]
I will merge everything as soon as you keep the original material light colors.
And keep muzei needed permission by default.
Thanks for everything you did.

**Comment by Train88** [comment]
No problem, I will fix those shortly.

**Comment by Train88** [comment]
I apologize, I made a couple errors last night. Everything should be fixed up now.

**Pull request merged**
